plugins {
    id 'com.gradleup.shadow' version '8.3.3'
}

architectury {
    platformSetupLoomIde()
    forge()
}

loom {
    accessWidenerPath = file('../common/src/main/resources/starlight.accesswidener')

    forge {
        convertAccessWideners = true
        extraAccessWideners.add(loom.accessWidenerPath.get().asFile.name)
        mixinConfig('starlight.mixins.json')
    }
}

configurations {
    common
    shadowCommon
    compileClasspath.extendsFrom configurations.common
    runtimeClasspath.extendsFrom configurations.common
    developmentForge.extendsFrom configurations.common
}

dependencies {
    minecraft "com.mojang:minecraft:${rootProject.ext.minecraft_version}"
    mappings loom.officialMojangMappings()

    forge "net.minecraftforge:forge:1.20.1-47.4.5"

    common project(path: ":common", configuration: "namedElements")
    shadowCommon project(path: ":common", configuration: "transformProductionForge")

    // MixinExtras
    implementation "io.github.llamalad7:mixinextras-forge:0.5.3"
    annotationProcessor "io.github.llamalad7:mixinextras-forge:0.5.3"
}

processResources {
    inputs.property 'version', project.version

    filesMatching('META-INF/mods.toml') {
        expand 'version': project.version,
               'minecraft_version': rootProject.ext.minecraft_version
    }
}

tasks.jar {
    archiveClassifier = 'dev'
}

tasks.shadowJar {
    exclude 'fabric.mod.json'
    exclude 'architectury.common.json'
    configurations = [project.configurations.shadowCommon]
    archiveClassifier = 'dev-shadow'
}

tasks.remapJar {
    inputFile = tasks.shadowJar.archiveFile
    dependsOn tasks.shadowJar
    archiveClassifier = null
}

tasks.sourcesJar {
    def commonSources = project(':common').tasks.sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.collect { zipTree(it) }
}
